name: yarn-build

on:
  push:
    branches: [ dev/runner-01, develop ]
  pull_request:
    branches: [ dev/runner-01, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependancies
        run: yarn install --frozen-lockfile

      - name: Create production build
        run: yarn build
